metal:
  children:
    masters:
      hosts:
              metal0: {ansible_host: 172.16.0.110, mac: '8e:55:63:b7:cd:a4', disk: sda, network_interface: ens18}
      metal1: {ansible_host: 172.16.0.111, mac: '86:b1:30:3f:7c:89', disk: sda, network_interface: ens18}
      metal2: {ansible_host: 172.16.0.112, mac: '0a:83:79:77:12:c1', disk: sda, network_interface: ens18}
    workers:
      hosts:
              metal3: {ansible_host: 172.16.0.113, mac: 'c2:a6:0b:a5:a6:a0', disk: sda, network_interface: ens18}
